In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
import re

In [51]:
# #Data from PFB Ref
# urls = [
#     'https://www.pro-football-reference.com/draft/2023-combine.htm',
#     'https://www.pro-football-reference.com/draft/2022-combine.htm',
#     'https://www.pro-football-reference.com/draft/2021-combine.htm',
#     'https://www.pro-football-reference.com/draft/2020-combine.htm',
#     'https://www.pro-football-reference.com/draft/2019-combine.htm',
#     'https://www.pro-football-reference.com/draft/2018-combine.htm',
#     'https://www.pro-football-reference.com/draft/2017-combine.htm',
#     'https://www.pro-football-reference.com/draft/2016-combine.htm',
#     'https://www.pro-football-reference.com/draft/2015-combine.htm',
#     'https://www.pro-football-reference.com/draft/2014-combine.htm',
#     'https://www.pro-football-reference.com/draft/2013-combine.htm',
#     'https://www.pro-football-reference.com/draft/2012-combine.htm',
#     'https://www.pro-football-reference.com/draft/2011-combine.htm',
#     'https://www.pro-football-reference.com/draft/2010-combine.htm',
#     'https://www.pro-football-reference.com/draft/2009-combine.htm',
#     'https://www.pro-football-reference.com/draft/2008-combine.htm',
#     'https://www.pro-football-reference.com/draft/2007-combine.htm',
#     'https://www.pro-football-reference.com/draft/2006-combine.htm',
#     'https://www.pro-football-reference.com/draft/2005-combine.htm',
#     'https://www.pro-football-reference.com/draft/2004-combine.htm',
    
# ]

# Define the start and end years
start_year = 2004
end_year = 2023

# Create a list of URLs for the specified range of years
urls = [
    f'https://www.pro-football-reference.com/draft/{year}-combine.htm' for year in range(start_year, end_year + 1)
]

holder = []

#need to use 0 index because that is the actual player dataframe
for url in urls:
    df = pd.read_html(url)[0]
    holder.append(df)
    time.sleep(2)

#concatenates all years
all_years_old = pd.concat(holder, ignore_index=True)

In [52]:
all_years_old

,Player,Pos,School,College,Ht,Wt,40yd,Vertical,Bench,Broad Jump,3Cone,Shuttle,Drafted (tm/rnd/yr)
0,Derek Abney,WR,Kentucky,College Stats,5-9,179,4.58,33.5,NaN,120,6.89,4.08,Baltimore Ravens / 7th / 244th pick / 2004
1,Nathaniel Adibi,DE,Virginia Tech,College Stats,6-3,254,4.65,33.0,NaN,118,NaN,4.36,Pittsburgh Steelers / 5th / 145th pick / 2004
2,Roc Alexander,CB,Washington,College Stats,5-11,185,4.35,39.5,NaN,125,6.97,4.23,NaN
3,Rich Alexis,RB,Washington,College Stats,6-0,210,4.64,32.0,NaN,114,7.41,4.43,NaN
4,Jared Allen,DE,Idaho State,NaN,6-6,265,4.72,33.0,13,120,7.11,4.34,Kansas City Chiefs / 4th / 126th pick / 2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6836,Luke Wypler,C,Ohio St.,College Stats,6-3,303,5.14,30.5,NaN,106,7.64,4.53,Cleveland Browns / 6th / 190th pick / 2023
6837,Bryce Young,QB,Alabama,College Stats,5-10,204,NaN,NaN,NaN,NaN,NaN,NaN,Carolina Panthers / 1st / 1st pick / 2023
6838,Byron Young,DT,Alabama,College Stats,6-3,294,NaN,26.0,24,108,7.68,NaN,Las Vegas Raiders / 3rd / 70th pick / 2023
6839,Byron Young,EDGE,Tennessee,College Stats,6-2,250,4.43,38.0,22,132,7.19,NaN,Los Angeles Rams / 3rd / 77th pick / 2023
6840,Cameron Young,DT,Mississippi St.,College Stats,6-3,304,5.10,NaN,NaN,NaN,NaN,NaN,Seattle Seahawks / 4th / 123rd pick / 2023

In [73]:
def extract_pick(pick):
    if pd.notna(pick):
        match = re.search(r'\d+', pick)
        if match:
            return int(match.group())
    return pick

In [74]:
# Split the 'Drafted (tm/rnd/yr)' column
drafted_info = all_years_old['Drafted (tm/rnd/yr)'].str.split(' / ', expand=True)

# Rename the columns
drafted_info.columns = ['Team', 'Round', 'Pick', 'Year']

# Concatenate the original DataFrame with the new 'drafted_info' DataFrame
all_years = pd.concat([all_years_old, drafted_info], axis=1)

# Drop the original 'Drafted (tm/rnd/yr)' column
all_years.drop(columns=['Drafted (tm/rnd/yr)', 'College'], inplace=True)

all_years.columns = all_years.columns.str.lower()
all_years['pick'] = all_years['pick'].apply(extract_pick)
all_years['pos'].value_counts()

WR      946
CB      677
RB      585
OT      467
S       462
DT      425
DE      423
TE      370
QB      366
OLB     360
OG      310
ILB     219
LB      179
C       158
OL      141
Pos     123
DL      120
P       118
EDGE    100
K        93
FB       84
DB       83
LS       32
Name: pos, dtype: int64

In [75]:
rbs = all_years[all_years['pos'] == 'RB']

In [76]:
rbs

,player,pos,school,ht,wt,40yd,vertical,bench,broad jump,3cone,shuttle,team,round,pick,year
3,Rich Alexis,RB,Washington,6-0,210,4.64,32.0,NaN,114,7.41,4.43,NaN,NaN,NaN,NaN
17,Tatum Bell,RB,Oklahoma State,5-11,212,4.37,38.5,25,117,NaN,NaN,Denver Broncos,2nd,41.0,2004
38,Ran Carthon,RB,Florida,5-11,224,4.51,34.5,22,112,NaN,4.12,NaN,NaN,NaN,NaN
51,Cedric Cobbs,RB,Arkansas,6-0,223,4.75,40.0,NaN,123,NaN,NaN,New England Patriots,4th,128.0,2004
63,Duron Croson,RB,Fort Valley State,6-1,226,4.83,30.5,14,108,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6784,Tyjae Spears,RB,Tulane,5-10,201,NaN,39.0,NaN,125,NaN,NaN,Tennessee Titans,3rd,81.0,2023
6794,Tavion Thomas,RB,Utah,6-0,237,4.74,30.0,NaN,118,NaN,NaN,NaN,NaN,NaN,NaN
6795,SaRodorick Thompson,RB,Texas Tech,6-0,207,4.67,32.5,NaN,120,7.25,4.70,NaN,NaN,NaN,NaN
6803,Sean Tucker,RB,Syracuse,5-9,207,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6810,Deuce Vaughn,RB,Kansas St.,5-5,179,NaN,35.5,NaN,116,NaN,NaN,Dallas Cowboys,6th,212.0,2023

In [77]:
all_years

,player,pos,school,ht,wt,40yd,vertical,bench,broad jump,3cone,shuttle,team,round,pick,year
0,Derek Abney,WR,Kentucky,5-9,179,4.58,33.5,NaN,120,6.89,4.08,Baltimore Ravens,7th,244.0,2004
1,Nathaniel Adibi,DE,Virginia Tech,6-3,254,4.65,33.0,NaN,118,NaN,4.36,Pittsburgh Steelers,5th,145.0,2004
2,Roc Alexander,CB,Washington,5-11,185,4.35,39.5,NaN,125,6.97,4.23,NaN,NaN,NaN,NaN
3,Rich Alexis,RB,Washington,6-0,210,4.64,32.0,NaN,114,7.41,4.43,NaN,NaN,NaN,NaN
4,Jared Allen,DE,Idaho State,6-6,265,4.72,33.0,13,120,7.11,4.34,Kansas City Chiefs,4th,126.0,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6836,Luke Wypler,C,Ohio St.,6-3,303,5.14,30.5,NaN,106,7.64,4.53,Cleveland Browns,6th,190.0,2023
6837,Bryce Young,QB,Alabama,5-10,204,NaN,NaN,NaN,NaN,NaN,NaN,Carolina Panthers,1st,1.0,2023
6838,Byron Young,DT,Alabama,6-3,294,NaN,26.0,24,108,7.68,NaN,Las Vegas Raiders,3rd,70.0,2023
6839,Byron Young,EDGE,Tennessee,6-2,250,4.43,38.0,22,132,7.19,NaN,Los Angeles Rams,3rd,77.0,2023
6840,Cameron Young,DT,Mississippi St.,6-3,304,5.10,NaN,NaN,NaN,NaN,NaN,Seattle Seahawks,4th,123.0,2023